### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#10]
Maybe this could be an option to the Text input…

**Comment by mbostock** [comment]
Here’s one place I’d want a textarea input: https://observablehq.com/@observablehq/daily-team-shuffler

**Comment by j-f1** [comment]
More examples: https://observablehq.com/@j-f1/sort-lines-of-text?collection=@j-f1/tools, https://observablehq.com/d/4f235f27b1be8f08. These notebooks also use textareas to display read-only output (which makes it easy to select all)
