### ISSUE TITLE
Add supported browsers to README

### ISSUE THREAD

**Issue by mootari** [observablehq/inputs#102]
`Input` uses the EventTarget constructor, which has only been available from Safari / iOS 14 onwards (released 2020-09-16). It might be worth mentioning known restrictions in the project's README.

For example, the [Tangle notebook](https://observablehq.com/@mbostock/tangle) makes use of the Input widget, and cannot be used with Safari 13 or earlier.

**Comment by mbostock** [comment]
Sorry, but I’m not planning on maintaining this information.
