### ISSUE TITLE
Format table header?

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#103]
What if you want to control how the column header is formatted?

Ref. https://github.com/observablehq/inputs/issues/68#issuecomment-775928317
Ref. https://github.com/observablehq/inputs/issues/83#issuecomment-776130781

**Comment by mbostock** [comment]
I could see this being specified as a function that takes a column name and returns a string or an HTML element, similar to the *label* option. For example, that might be useful to replace underscores with spaces.

**Comment by mootari** [comment]
I think I'd prefer to see this implemented as a per-column setting:
- If the value is static, use it as suggested in your comment.
- If the value is a function, pass in `(column, order)`, where order is one of -1 (descending), 0 (none), 1 (ascending). The function returns the column header representation, including the sort indicator. This allows for opinionated indicator symbols like "↑" and "↓" and custom placement, or even column labels which adjust to the order, in cases where the inferred meaning may not be immediately obvious to the viewer.

**Comment by mootari** [comment]
To add another use case: Column labels could get replaced with icons. In the following example, the label "comments" takes up unneccessary space, even though the column values rarely exceed a single digit:

![image](https://user-images.githubusercontent.com/322014/109993683-d7e32800-7d0c-11eb-8d75-59e633f025d3.png)
