### ISSUE TITLE
Textarea resize

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#107]
There should be a way to disable resizing, or at the least, if the rows is equal to the maxheight it should be disabled by default since resizing isn’t allowed anyway.

**Comment by jrus** [comment]
Here's one way:

```javascript
viewof box = {
  var box = Textarea()
  box.querySelector('textarea').style = 'resize: none;'
  return box
}
```

**Comment by jrus** [comment]
Here's one way:

```javascript
viewof box = {
  var box = Textarea();
  box.querySelector('textarea').style = 'resize: none;'
  return box;
}
```

**Comment by jrus** [comment]
As a reader though I'd prefer if authors just left the browser text boxes alone, and didn't try to disable resize.

**Comment by mbostock** [comment]
Also, there should be a way to have auto resize, so that the textarea expands to fit its content.
