### ISSUE TITLE
Support Buttons with undefined as initial value

### ISSUE THREAD

**Issue by mootari** [observablehq/inputs#112]
A fairly frequent use case for buttons is to delay a computationally expensive action until the user starts it explicitely. This can be achieved by creating a `viewof` with a `<button>` element and assigning it a value of `undefined`:
```js
viewof start = Object.defineProperty(html`<button>Start`, 'value', {value: undefined})
```
Because the Runtime uses `Generators.input()` for viewof, downstream cells won't run until the button has been clicked:
```
count = start, (this || 0) + 1
```

Button inputs can be assigned an arbitrary value. However, the input does not explicitely check if a `value` option has been declared, expectedly treating a value of `undefined` as "not provided".

**Suggested solutions**

- Explicitely check if the property `value` has been defined, via `options.hasOwnProperty('value')`. If the value is `undefined`, apply it as button value.
- Alternatively, apply an initial value of `null` as `undefined`.
- Alternatively, allow the `required` option for buttons. If specified, the initial value is set to `undefined`.
- Alternatively, provide a dedicated `Trigger` input.

**Comment by mbostock** [comment]
I like the *required* option idea.
