### ISSUE TITLE
Make the number input wider with Range?

### ISSUE THREAD

**Issue by Fil** [observablehq/inputs#113]
it can be quite misleading if you read the input as being the value: this very pricey house suddenly seems to cost 10 thousands:
<img width="770" alt="Capture d’écran 2021-03-03 à 17 57 23" src="https://user-images.githubusercontent.com/7001/109842328-4317f600-7c4a-11eb-99d3-2302f3cee297.png">

**Comment by tophtucker** [comment]
Yeah I've been wondering about this. I think it's rare that people need more than 5 _significant_ digits; here it's just a problem of zeroes.

At first I tried using the `format` option to take off three zeroes, but that breaks the text input (and fails validation). Then I thought maybe `transform`/`inverse` were the answer, but I guess they only affect slider mapping, not number display.

I should probably just label it `Home price ($k)` and multiply it by 1000 elsewhere. But that makes me want something like the Button's `reducer` option on all Inputs — something that takes the raw input value and returns a transformed version to be set as the node's .value. But maybe that'd break `.bind`. Hm…

**Comment by mbostock** [comment]
I don’t think this is a bug per se — this is just how the native number input handles a number that’s too big to fit, and we can’t control that. We could increase the width of the number input here, but there’s always going to be a number that’s too big to fit.

**Comment by mbostock** [comment]
Here are a few workarounds.

Make the input wider using *width*:

<img width="462" alt="Screen Shot 2021-04-07 at 10 32 37 AM" src="https://user-images.githubusercontent.com/230541/113910128-55c3a480-978d-11eb-908f-f40cd9be1e08.png">

```js
Range([0, 1e7], {label: "Home price", value: 6e5, width: 320, step: 1e4})
```

Use thousands via a *transform*:

<img width="383" alt="Screen Shot 2021-04-07 at 10 34 32 AM" src="https://user-images.githubusercontent.com/230541/113910125-55c3a480-978d-11eb-83e2-db40c5d11dd2.png">

```js
Range([0, 1e4], {label: "Price (thousands)", transform: d => d * 1e3, value: 6e2, step: 1e1})
```

Apply a custom style:

<img width="380" alt="Screen Shot 2021-04-07 at 10 37 51 AM" src="https://user-images.githubusercontent.com/230541/113910124-552b0e00-978d-11eb-999e-25be45c154f8.png">

```js
{
  const r = Range([0, 1e7], {label: "Home price", value: 6e5, step: 1e4});
  r.querySelector("[type=number]").style.flexShrink = 1;
  return r;
}
```

I think the last one would be nice as an option, but I’m not sure exactly how to express it.

**Comment by Fil** [comment]
Very good methods to fix the problem when you are aware of it.

I guess my point is that we don't get any visual feedback when it happens: iow I was looking for a way to display some kind of red flag.

Piggy-backing on your flexShrink (TIL!) example, I'd like to have style.textOverflow = 'ellipsis' *by default*

~~~js
{
  const r = Range([0, 1e7], { label: "Home price", value: 6e5, step: 1e4 });
  r.querySelector("[type=number]").style.textOverflow = 'ellipsis';
  return r;
}
~~~

However this is valid only when the value is integer, we don't want the ellipsis to kick in for digits after the comma (!).
