### ISSUE TITLE
Table: Change vertical cell alignment to top

### ISSUE THREAD

**Issue by mootari** [observablehq/inputs#119]
Cell content is vertically centered. If a cell has a larger height than its siblings (e.g. when displaying multiple rows of text), then locating a single-line value in a sibling cell can be difficult, because the margin between cell value and row separators can vary widely.

**Suggested solution**

Align cell content at the top of a row, by adding the following CSS rule:
```css
.__ns__-table td {
  vertical-align: text-top;
}
```
Note that this change has no effect on single-line, text-only rows.

**Workaround**

Inject a custom style into the widget:
```js
const table = Table(data);
table.appendChild(html`<style>#${table.id} td {vertical-align: text-top}`);
return table;
```

**Comment by mbostock** [comment]
The Table currently assumes that cells are a fixed height of 22px. Next assigns a default vertical-align to td and th, and we may port this to Classic, but I don’t think I’m going to add it to the default Table style in inputs.
