### ISSUE TITLE
Table consumes iterables multiple times

### ISSUE THREAD

**Issue by domoritz** [observablehq/inputs#123]
I noticed that `Table` consumes the full iterator before rendering the rows. I would expect that the iterator gets consumed only once and only while the user scrolls in the table. The problem with the current behavior is that iterators sometimes cannot rewind or are expensive to create again. 

If I understand https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols correctly, it should be okay to implement an iterator where `[Symbol.iterator]` just returns the same iterator for an object.

<img width="1393" alt="Screen Shot 2021-03-22 at 12 24 32" src="https://user-images.githubusercontent.com/589034/112046664-907cda00-8b09-11eb-88e8-aa10f6997a8c.png">

See the problem in https://observablehq.com/d/d91b4879db425ea9

**Comment by j-f1** [comment]
This is caused by [`lengthof`](https://github.com/observablehq/inputs/blob/bf525033948bbdda452e65bc06c09a6b42f3b06c/src/table.js#L305-L312), which requires a `length`, `size`, or `numRows()` attribute. Maybe it should return `null` in case of failure, and have the main `table` function convert the iterator into an array if the length is `null`.

**Comment by domoritz** [comment]
That's not good for cases where we don't know the size of the result upfront (such as in a stream). In my case, it's expensive to iterate over the results so it would be nice to avoid having to materialize the whole iterator.

**Comment by mbostock** [comment]
Yeah, it should be possible to avoid computing `N` upfront, and instead lazily query the iterator to determine if there are additional rows to display when scrolling.

**Comment by mbostock** [comment]
Ah, I was wrong, this will be tricky because the Table input also uses iterator to determine the type of each column. So to support this will require Table to accumulate the already-visited rows. I’m going to relabel this as a request for enhancement because destructive iterators are not currently supported.

**Comment by domoritz** [comment]
We actually just fixed our iterator and made it rewindable. It would still be great if Table did not consume the full iterator multiple times.

Would it make sense not to need the size anymore and to determine the types based on a sample?

**Comment by mbostock** [comment]
The types are already based on a sample — it only consumes up until the first non-nullish value:

https://github.com/observablehq/inputs/blob/bf525033948bbdda452e65bc06c09a6b42f3b06c/src/table.js#L295-L303

I suspect we could remove the lengthof iteration. You’d still need a nondestructive iterator, but it would avoid iterating over all the data in the common case, improving performance. We’d need to replace the code that looks at `N` to check whether there are still more data available in the iterator. It’ll be a little tricky to implement this indeterminate check, though.

https://github.com/observablehq/inputs/blob/bf525033948bbdda452e65bc06c09a6b42f3b06c/src/table.js#L201

**Comment by domoritz** [comment]
Not needing the size would be great and greatly improve the performance in our use case where we stream results.

**Comment by domoritz** [comment]
Do I see it correctly that `reinput` only happens after materialization (or can it be called from the outside)? If yes, we could get the size from the index instead.
