### ISSUE TITLE
Table row height calculation is off.

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#126]
It seems too short.

**Comment by jrus** [comment]
It also fits even less if you put taller content in the cells.

**Comment by mbostock** [comment]
Table isn’t designed for variable-height cells.

**Comment by jrus** [comment]
The height doesn't necessarily vary from row to row. But there at least a few examples I have seen in published notebooks where taller content was consistently stuck into every row. Table is handy for this even if it was not explicitly intended to support this use –  an author making such a table can know to multiply `rows` by some constant to get the number they want.

**Comment by mbostock** [comment]
The issue here is that Observable’s default styles are overriding Table’s default styles. With just Table’s styles, each row is 22px; with Observable’s styles applied, each row is 26px tall. I need to make these consistent.
