### ISSUE TITLE
Range default value is not (max+min)/2 but 50

### ISSUE THREAD

**Issue by stardisblue** [observablehq/inputs#134]
As said in the title, I made a notebook to illustrate it :).

https://observablehq.com/@stardisblue/observable-range-input-behaviour

tested on Firefox 87.0, Chrome 89.0.4389.114

**Comment by mbostock** [comment]
Ah, I’ve been testing in Safari 😐 

<img width="1000" alt="Screen Shot 2021-04-11 at 10 07 13 AM" src="https://user-images.githubusercontent.com/230541/114313995-b9134680-9aad-11eb-8db5-7fe723d718f5.png">
