### ISSUE TITLE
Table option to suppress checkbox column

### ISSUE THREAD

**Issue by CobusT** [observablehq/inputs#136]
I see many uses of Table to just view the results in a table format without the need to have the table drive further down-selection. Although the checkboxes on the left are great for having the table drive the next steps (selected rows) it would be great to have an option to have the table without this column.

Perhaps an option like 'selectable' with a default of true?

**Comment by mootari** [comment]
"disabled" would seem like a sensible choice?

**Comment by mbostock** [comment]
I think disabled would retain the checkboxes, but in a disabled state. I think I’d prefer a *select* option.

**Comment by CobusT** [comment]
For now, as a workaround, I am adding this style sheet to Inputs.table where I want to hide the first column:
`  .nocheckbox td:nth-child(1), .nocheckbox th:nth-child(1) {
    display: none;
  }
  .nocheckbox td:nth-child(2), .nocheckbox th:nth-child(2) {
    padding-left: 0px;
  }`

**Comment by shancarter** [comment]
For a css fix that wouldn't break the layout, we could consider `visibility: hidden` which should just toggle the visibility without affecting layout. https://developer.mozilla.org/en-US/docs/Web/CSS/visibility
