### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by tophtucker** [observablehq/inputs#139]
Especially in spreadsheet-like or calculator-like notebooks, I find myself wanting to show an output (sometimes TeX) that’s labeled and aligns with inputs, unlike an inspector value. So an `<output>`-like Input could be handy, even if it's a sorta oddball, even more so than Table, and trivial except for the responsive layout/formatting.

**Comment by tophtucker** [comment]
or i can just happily use this ha https://observablehq.com/@tophtucker/lil-output

**Comment by mbostock** [comment]
I recommend a readonly Text (or Textarea) input:

```js
Text({value: "hello", label: "Output", readonly: true})
```

Or if you want a helper:

```js
function Output(options) {
  return Text({...options, readonly: true});
}
```

**Comment by mbostock** [comment]
I think a readonly Inputs.text is probably fine?
