### ISSUE TITLE
Nit: required is not a good name for selection control on Table

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/inputs#149]
_required_ as an option name on Table is not very intuitive. There is a polarity issue (I just set required: true to say a selection is required and expected the result not to resolve when nothing was selected like radio) and it's not clear what noun is being required (it could mean, a sort order is required). I am not sure how you landed on required: false with the default being true, thats counter to my normal expectation for options defaulting to false (e.g. bubbles).

**Comment by Fil** [comment]
reference issue https://github.com/observablehq/inputs/issues/104

**Comment by mbostock** [comment]
Thanks for the feedback. I don’t know of a better name, and I don’t want to break backwards compatibility, so I’m not going to change this now. If you have suggestions of a better name feel free to share them, and if this continues to be a point of confusion then we can deprecate the old option and introduce a new one. Also note that there will likely be a new option to support suppressing interaction on tables #136.
