### ISSUE TITLE
Table pushed to the left when embedding

### ISSUE THREAD

**Issue by CobusT** [observablehq/inputs#150]
When using a table outside of the notebook environment (e.g. in a React app), the form element is positioned too far too the left. 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/10869236/119560228-84ef9e80-bd58-11eb-928c-51df7937b007.png">

It looks like it is getting it from this style:

https://github.com/observablehq/inputs/blob/c868be98847171987a2a0929674b534e76e3ede1/src/style.css#L186

**Comment by mbostock** [comment]
I don’t think we can fix this without breaking the styles on Observable. I’d suggest adding padding to the parent container when used in React, or overriding the styles.

**Comment by CobusT** [comment]
ok.
