### ISSUE TITLE
Options are not correctly passed along for selections.

### ISSUE THREAD

**Issue by somethingelseentirely** [observablehq/inputs#157]
According to the documentation there are quite a few options on `select`, however they are not passed correctly to the underlying `chooser` implementation and therefore never work.

https://github.com/observablehq/inputs/blob/8fbbcf76f40445346637a764825454e4f7fcc76f/src/chooser.js#L13

**Comment by mbostock** [comment]
Which options, specifically, are you suggesting do not work?

The options are documented here: https://github.com/observablehq/inputs#Select
And they are demonstrated here: https://observablehq.com/@observablehq/input-select

I can’t find any that don’t work, but if you can demonstrate what’s not working I would be happy to take another look.
