### ISSUE TITLE
Bug with value/multiple options for Inputs.table?

### ISSUE THREAD

**Issue by gordonje** [observablehq/inputs#159]
Hello!

I encountered some unexpected behavior when trying to pre-select a table row (using the `value` option) when the `multiple` option is set to `true`.

Demonstrated in [this notebook](https://observablehq.com/d/d492cf005669d142))

I intended to allow users to select a year option that drives some dynamic behavior in the notebook. Would otherwise use a `select` input for this, but a `table` affords display of some summary information about the year *before* the user selects it.

Say my data looks like this:

```js
rows = [
  {year: 2020, count: 40},
  {year: 2019, count: 30},
  {year: 2018, count: 20},
  {year: 2017, count: 10},
]
```

This works as expected, with on row selected:

```js
viewof selectedRowMulti = Inputs.table(
  rows,
  {
    // multiple: true, // set by default
    required: false,
    value: rows.filter( d => d.year === 2020 ),
    width: '25%',
    format: {
      year: d => d3.format('d')(d)
    }
  }
)
```

However, attempting to set the `multiple` option to `false` (with all other options the same) yields no selections.

```js
viewof selectedRowSingle = Inputs.table(
  rows,
  {
    multiple: false,
    required: false,
    value: rows.filter( d => d.year === 2020 ),
    width: '25%',
    format: {
      year: d => d3.format('d')(d)
    }
  }
)
```

**Comment by mbostock** [comment]
When multiple is false, the value is a single row rather than an array of rows. Try using array.find instead of array.filter to set the value.

**Comment by gordonje** [comment]
@mbostock That did it! Thank you for this and all the other cool stuff you do.
