### ISSUE TITLE
Inputs.table() for an array of primitives

### ISSUE THREAD

**Issue by dunstan** [observablehq/inputs#160]
I was expecting Inputs.table() to show me a list of these filenames, but instead it broke each letter out into its own cell.

![image (2)](https://user-images.githubusercontent.com/1316196/124012120-9ea68600-d995-11eb-9e63-3b17b2a78ba1.png)

[Slack thread](https://observablehq.slack.com/archives/C01N0F9GPHV/p1625075853119500):
<img width="547" alt="image" src="https://user-images.githubusercontent.com/1316196/124012139-a6fec100-d995-11eb-9320-a300349a3cd5.png">

Code:
```
dogZip = FileAttachment("Dog_Photos.zip").zip()
dogZip.filenames
Inputs.table(dogZip.filenames)
```

Zip file:
[Dog_Photos.zip](https://github.com/observablehq/inputs/files/6743170/Dog_Photos.zip)

**Comment by visnup** [comment]
More bluntly, `Inputs.table(["hello", "there"])` _could_ smartly output a table like:

string | 
------ |
hello |
there |

**Comment by mbostock** [comment]
If we special-case strings, we should special-case all primitive values (numbers, booleans too, and possibly null and undefined).

**Comment by tophtucker** [comment]
noticed & documented by @triptych https://observablehq.com/@triptych/how-to-get-around-flat-array-issue-in-observable-tables
