### ISSUE TITLE
accept a data Promise?

### ISSUE THREAD

**Issue by Fil** [observablehq/inputs#170]
It would make dataflow easier if data could be a Promise—Inputs.table(data, options) would then return a promise to the table view of the data.

and the user could give:
> viewof values = Inputs.table(FileAttachment("parameters.csv").csv())

A simple indirection does it:
~~~diff
diff --git a/src/table.js b/src/table.js
index 4da75b3..3914fb1 100644
--- a/src/table.js
+++ b/src/table.js
@@ -8,7 +8,11 @@ import {defined, ascending, descending} from "./sort.js";

 const rowHeight = 22;

-export function table(
+export function table(data, options) {
+  return data instanceof Promise ? data.then(data => table0(data, options)) : table0(data, options);
+}
+
+export function table0(
   data,
   {
~~~

This might be useful also for Inputs.select and others, but it might add more complication than value. I don't think it would be reasonable to scour the options object for promises, for example.

A difficulty however is that, if something expects the function to return a DOM node (for example to insert it in a dahsboard), it will have to apply the same logic. An alternative would be to throw a more informative error (i.e. `the data is a Promise, please await`, instead of `TypeError: e is not iterable`).

(A similar thing might be useful in Plot, with the same caveat that if something—say, a plugin—expects to receive a svg element, it will have to also test for Promises.)

**Comment by mbostock** [comment]
I think that Inputs.table should always synchronously return an HTMLTableElement. The difference is when the data is a promise, the contents are lazily filled when the promise resolves.
