### ISSUE TITLE
When assigning the value of a range input, implicitly correct invalid values?

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#176]
The introduction of Inputs.number subtly changed the behavior of Inputs.range. Whereas previously it would implicit correct invalid values on assignment, for example rounding to the nearest integer when *step* = 1, now it currently ignores invalid values on assignment. Essentially this boils down to the difference in behavior between a type=range input and a type=number input:

```js
{
  const input = htl.html`<input type=range min=0 max=100 step=1>`;
  input.value = 115.5;
  return [input.valueAsNumber, input.checkValidity()]; // returns [100, true]
}
```
```js
{
  const input = htl.html`<input type=number min=0 max=100 step=1>`;
  input.value = 115.5;
  return [input.valueAsNumber, input.checkValidity()]; // returns [115.5, false]
}
```

We should mirror this behavior with Inputs.number and Inputs.range, most like, or better, we should have an option that lets you control whether invalid values are autocorrected or ignored (and we could have the default value be autocorrect for range, but ignore for number).

**Comment by mbostock** [comment]
Another example reported here https://observablehq.com/@observablehq/input-range#comment-b453abb193a4863d

**Comment by Fil** [comment]
Yet another example reported in https://observablehq.com/@martien/arc ; uploading #180 fixed it.
