### ISSUE TITLE
Inputs do not play with nanomorph

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/inputs#184]
I was hoping to change static configuration dynamically, e.g. adding options to a drop down, then reconciling the new component with the old: https://observablehq.com/@tomlarkworthy/juice

However, Inputs do not seem to play with nanomorph (focussed repro https://observablehq.com/@tomlarkworthy/nanomorph-inputs-bug).

Not sure if this would be considered a bug but I want to formally record this issue (I have not dug into why quite yet, but I probably will return to it)

**Comment by mbostock** [comment]
I don’t think we should expect this to work. Inputs have internal state, and their value isn’t considered part of the DOM; so while nanomorph can update the DOM, Inputs shouldn’t have to use a MutationObserver or some other listening mechanism to detect when a third-party has changed the DOM and try to infer what its new value should be. Maybe this would work if Inputs were implemented as custom elements, but we don’t have any plans to do that currently. Thanks for the report.
