### ISSUE TITLE
e.closest is not a function

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/inputs#197]
If Inputs.bind is used on a non-DOM target, the disposal.js logic throws an exception

the invalidation default is assuming element is a DOM node
https://github.com/observablehq/inputs/blob/f727b514cbe10fb42b06672d4cefa1003572263d/src/bind.js#L4

**Comment by mbostock** [comment]
Yep, as documented. You’ll want to pass in something else if you want different behavior.
