### ISSUE TITLE
Search doesn't filter Arquero tables

### ISSUE THREAD

**Issue by mkfreeman** [observablehq/inputs#198]
When an Arquero table is passed to `Inputs.search`, the result is always the total number of rows (it is not filtered). See this [canvas](https://observablehq.com/@observablehq/search-doesnt-filter-arquero-tables). 

```
// The result of the search is always the total number of rows
viewof searched = Inputs.search(aq.from(data), {label:"search the data:"})
```

<img width="647" alt="Screen Shot 2021-11-10 at 8 29 14 AM" src="https://user-images.githubusercontent.com/1373882/141121818-25232c7c-7598-4e48-a88a-5619883a0847.png">

**Comment by hellonearthis** [comment]
Is that link correct?

**Comment by mbostock** [comment]
Strange. It looks like it should work, but there must be something weird happening.
