### ISSUE TITLE
Add some space between multiple buttons?

### ISSUE THREAD

**Issue by tophtucker** [observablehq/inputs#201]
Could we add some space between buttons in the case where you pass an array to Input.button? Maybe there are tricky interactions in other cases and it’s a little thing but it’s been enough to stop me from using the multi-button capability in the past.

As seen in the lovely https://observablehq.com/@theeconomist/lucy-mission-animation:
<img width="285" alt="15BD917A-09A3-4510-B136-2F6BC55FA1FA-764-000445D67CEBC350" src="https://user-images.githubusercontent.com/841829/142305972-91664584-2892-4653-9379-842aaba15da0.png">

With gap: 3px:
<img width="291" alt="0A680F08-59A6-4977-96F8-1679482A5DF2-764-000445D6FC6762ED" src="https://user-images.githubusercontent.com/841829/142305994-ea04379d-5bed-4861-944c-64b8cc77c43a.png">

**Comment by mbostock** [comment]
Fasincating. Safari does that by default:

<img width="299" alt="Screen Shot 2021-11-17 at 4 24 15 PM" src="https://user-images.githubusercontent.com/230541/142309360-18798aea-91c9-4a3e-bcce-eee175dcfa56.png">

**Comment by mootari** [comment]
The empty space in Safari is part of the button design:
![image](https://user-images.githubusercontent.com/322014/142317951-e111f28b-3f7d-44dc-8eb2-d7fd0229e748.png)

**Comment by tophtucker** [comment]
oh! 🧐 well… then i'm not sure what to do. i can live with it lol

**Comment by mootari** [comment]
Actually, I'd like to second this request, as both Chrome and Firefox lack any kind of spacing. I don't think that Safari should be used as the optimization target here.

**Comment by mootari** [comment]
In the meantime, here are two workarounds with minimal overhead:

To apply button spacing globally, add an HTML cell with the following content:
```css
<style>.${Inputs.text().classList[0]} button+button {margin-left:.5em}
```
If instead you want to apply spacing (or any other styles) to individual elements, add the following helper to your notebook:
```js
function applyStyle(element, rules) {
  for(const [selector, definition] of Object.entries(rules)) {
    for(const n of element.querySelectorAll(selector)) n.style.cssText += definition;
  }
  return element;
}
```
then use it like this:
```js
viewof init = applyStyle(Inputs.button([
  'rotated',
  'rotated-180',
  'shuffled',
  'sorted',
  'sorted-reverse',
].map(v => [v, () => v]), {
}), {
  'button+button': 'margin-left:.5em',
  'button': 'white-space:nowrap',
})
```

**Comment by mootari** [comment]
@mbostock The fix hasn't been published yet. Would you be willing to create a new release?
