### ISSUE TITLE
Inputs.file(url:{http(s):/address})

### ISSUE THREAD

**Issue by kimmolinna** [observablehq/inputs#203]
Input file from a http(s)-address to memory.

**Comment by mbostock** [comment]
I’m guessing this is a duplicate of #192? If not, please let me know more specifically what you are asking for.

If you want a FileAttachment-like object for a given URL, see https://github.com/observablehq/stdlib/issues/245.

**Comment by kimmolinna** [comment]
Thank you very much. I meant exactly observablehq/stdlib#245. I would like to load parquet-files from web.
