### ISSUE TITLE
Create searchable select menus

### ISSUE THREAD

**Issue by mkfreeman** [observablehq/inputs#207]
When a Select menu has many options, scrolling through them is tedious. Creating a searchable option for `Inputs.select` (e.g., `{searchable: true}`) would allow users to search through a long list of options, such as U.S. counties. As a reference, see [react-select](https://react-select.com/home)

https://user-images.githubusercontent.com/1373882/147106292-298079ad-84e4-4811-8f70-eafca351da21.mp4

**Comment by mbostock** [comment]
The native way of doing this is a text input with a datalist option. I don’t think we plan on implementing any non-native inputs in this library (due to complexity).

**Comment by mkfreeman** [comment]
Noted! Do you think this is a worthwhile functionality to prototype? Looks fairly [straightforward](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist).

**Comment by mbostock** [comment]
It’s already implemented on Inputs.text and Inputs.search. 😄

**Comment by mkfreeman** [comment]
I see! I didn't know that you could set a datalist on a text input (e.g., [here](https://observablehq.com/@observablehq/input-text#state). Exactly what I wanted!
