### ISSUE TITLE
Support for "Max Selected" option with checkbox

### ISSUE THREAD

**Issue by youbastard** [observablehq/inputs#209]
I'd like to be able to optionally limit the amount checkboxes that can be selected at once, while using `Inputs.checkbox()`.

The notebook below demonstrates how this feature can currently be accomplished:
https://observablehq.com/@youbastard/adding-a-max-selected-option-to-inputs-checkbox

A suggested approach would be to add a integer `max` property to the options object.

```
Inputs.checkbox(['a', 'e', 'i', 'o', 'u'], {
  label: 'Select your favorite vowels (max 3)',
  max: 3
});
```

**Comment by Fil** [comment]
This might feel a bit frustrating in terms of UX? If I had such a requirement I guess I'd rather unselect the "oldest" element when a new element is clicked. But any way it seems too non-standard to include in this module. (But, thank you for sharing the demo workaround!).
