### ISSUE TITLE
Is there a way to incorporate an asynchronous validation function specifically for the Inputs.text feature?

### ISSUE THREAD

**Issue by kasivisu4** [observablehq/inputs#250]
The validation function of inputs.text fails when the validation function is an async function. 
I have reproduced the issue [here](https://observablehq.com/@kasivisu4/inputs-text-validation-bug)

**Comment by mootari** [comment]
I believe that works as designed. I recommend to reframe it as a feature request.

**Comment by kasivisu4** [comment]
Oh makes sense @mootari. Thanks, I will update it as feature

**Comment by mbostock** [comment]
Input validation has to be synchronous. You can’t defer validation because you can’t delay the propagation of events when the input changes.
