### ISSUE TITLE
Simple checkbox

### ISSUE THREAD

**Issue by Fil** [observablehq/inputs#35]
Maybe it’s just an alias. It’d be nice if the exposed value was true/false, too.

**Comment by j-f1** [comment]
I don’t think this is resolved. There’s no input that produces a truthy value when checked and a falsy value when unchecked. Perhaps `Toggle` is a better name?

**Comment by mbostock** [comment]
I agree we could offer a dedicated single-checkbox component with a boolean value (or possibly, a pair of arbitrary values). It’s not high on my priority list given that you can already do this with Checkbox or Radio, though.

```js
viewof xs = Checkbox(["Do the thing"])
```
```
x = xs.length > 0
```
