### ISSUE TITLE
Number

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#39]
Like a Range, but where the range input is suppressed and only the number is visible. I suppose it could be Range({range: false}), but that’s a little weird.

**Comment by mbostock** [comment]
This can also sort of be done with `Text({type: "number"})`, though that’s a little weird, and it doesn’t support passing through the *min*, *max*, and *step* attributes.

**Comment by septatrix** [comment]
Definitely would like this one. I spend half an hour trying to build something like this but as I am new to views and observable I was unable to build anything satisfactory. Alternatively it would already be a huge help if one of the input/interactivity notebooks would provide a sample how such a thing could be build

**Comment by septatrix** [comment]
My intuitive guess would have been that a `Text({type: "number"})` would automatically parse as an integer similar to `Generators.input`. I agree that Number is probably a bad name should this become a standalone type.

**Comment by mbostock** [comment]
I think we’ll probably want `Range([min, max], {type: "number"})` or `Range([min, max], {range: false})`, since otherwise the function signature should be identical to Range, not Text.

**Comment by septatrix** [comment]
My use case would be a number input without a maximum

**Comment by tophtucker** [comment]
i've found myself using `Inputs.text({type: "number"})` a fair amount, and just ran into a case where i missed the min & max and was sorta surprised it didn't work. (figma api accepts a scale param of 1, 2, 3, or 4; slider invites too much expensive fiddling and evokes too much continuity, but radio or select evokes too little continuity. type="number" felt right!)

**Comment by septatrix** [comment]
Could this also please support numeric inputs without an upper bound? (As that does not seem to be the case in the above commit)

**Comment by mbostock** [comment]
@septatrix Yes, you can do that; use Infinity as the upper bound. In this case the value of the input will not be initialized unless you set one explicitly. For example:

```js
Inputs.number([0, Infinity], {value: 0, step: 1})
```

(Note that I had to fix a few things in 0.9.4.)
