### ISSUE TITLE
Typing in or incrementing Range’s formatted number input jumps

### ISSUE THREAD

**Issue by tophtucker** [observablehq/inputs#51]
E.g. if you have

`Range([1000, 10000], {format: d => d / 1000})`

then when you slide to 2000, the number input will read `2`. But if you focus it and increment with buttons or arrow keys, it’ll jump to its unformatted minimum, 1000. And you can't enter `3` for 3000. 

I don't know how to handle; it's thorny because the formatter isn't easily or necessarily invertible.

**Comment by mbostock** [comment]
I don’t think this is fixable. The formatter has to be idempotent—it can’t change the meaning of the number. If you want to transform the value, you probably should do it outside the input, e.g.

```js
viewof x = Range([1, 10])
```
```
xk = x * 1000
```
