### ISSUE TITLE
Make Table columns check more robust?

### ISSUE THREAD

**Issue by jheer** [observablehq/inputs#59]
Thanks for all these great input widgets! However, the `Table` viewer currently fails to correctly visualize an Arquero table when it is passed in directly as input, even though the table will correctly serialize to an array of objects with `arrayify` / `Array.from`.

The problem is that Arquero tables also have a `columns()` method, which the `Table` utility tries to `arrayify` to get the column names. The result is an empty array, and hence a table view with zero columns.

Are you open to having `Table` perform more careful input validation? For Arquero, a type check (e.g., `typeof columns === 'function'` in [Line 22](https://github.com/observablehq/inputs/blob/main/src/table.js#L22)) would suffice, but there may be more robust or flexible alternatives you might prefer. As things currently stand, the utility could also break with other iterable inputs if they also have a defined `columns` property (which, for a table abstraction, wouldn't be all that surprising).

(First raised in uwdata/arquero#89.)

**Comment by jheer** [comment]
Update: it looks like the `Search` utility also exhibits this issue. A type check could be added at search.js L14.

**Comment by mbostock** [comment]
Yes, we can add a helper that checks that data.columns is an array, and ignore it if it is not.
