### ISSUE TITLE
Dispatch "click" if source is a button?

### ISSUE THREAD

**Issue by severo** [observablehq/inputs#61]
In:

https://github.com/observablehq/inputs/blob/f72d22b4a8302922d1f86adb15fdfe6289950254/src/bind.js#L5-L6

if `source` is a special case (button, submit, file), shouldn't the custom event be `click` or `change` for consistency?

**Comment by mbostock** [comment]
That sounds right, yeah. We should say *sourceEvent* there, not hard-code “input”.

**Comment by mbostock** [comment]
Here’s the intended usage, for the record:

```js
viewof b = html`<button>Primary button`
```
```
bind(html`<button>Secondary button`, viewof b)
```

When this is fixed, `b` will now react as intended to the secondary button.
