### ISSUE TITLE
Validate function for Text input?

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#62]
Maybe we could offer a *validate* option that lets you check whether the current value is valid, and not expose the input to the rest of the application if so, and it could default to *input*.checkValidity so that it’s compatible with the already-supported *minlength*, *maxlength*, *pattern* etc. options. Those options do issue a warning, but they don’t currently prevent the invalid value from being exposed, and I think they should.

**Comment by mbostock** [comment]
If the input is invalid we could also disable the submit button (if present).

**Comment by mootari** [comment]
Note that this may require a list of custom validation messages for default checks like value range, required fields etc, because the native messages are displayed in the browser language. At least in my tests it felt awkward to have a mix of German browser-supplied messages and English custom messages.

**Comment by mbostock** [comment]
I think the solution to the mixed-language issue is to tell the browser that the forms are in English. #63 Haven’t tried it yet though. Let me know if it works. 😁

**Comment by mootari** [comment]
> Let me know if it works. 

Nope, sadly not. 😞  Also, I couldn't dig up any other info besides the common oninvalid + customValidity combo.

**Comment by mbostock** [comment]
Hmm. The *validate* function could return a string that could be passed to setCustomValidity, though.

**Comment by mootari** [comment]
Yes. You'll have to decide wether you want to pass the return value through (awkward empty string for "no error"), or if you want to sanitize falsy return values from validate() to empty strings, so that the user doesn't have to bother with that.

**Comment by mbostock** [comment]
Yeah, having validate return a truthy value (a non-empty string) when the input is *invalid* feels weird. Maybe I’ll start with just truthiness and punt on custom messages.

**Comment by mbostock** [comment]
Going with something like this:

```js
function checkUppercase(text) {
  if (text.value !== text.value.toUpperCase()) {
    text.setCustomValidity("Use uppercase");
    return false;
  }
  text.setCustomValidity("");
  return true;
}
```

And the default implementation is:

```js
function checkValidity(text) {
  return text.checkValidity();
}
```

**Comment by mootari** [comment]
How do you plan to handle the invalid event?

**Comment by mbostock** [comment]
What do you mean?

**Comment by mbostock** [comment]
PR in #64 if you’d like to review.

**Comment by mootari** [comment]
> What do you mean?

Having any form of validation will toggle the browser's native error message on submit, unless you call .preventDefault for `invalid` events.

**Comment by mbostock** [comment]
Sorry, I don’t understand what you mean. We want the browser’s native error messages to appear on submit?

**Comment by mootari** [comment]
> We want the browser’s native error messages to appear on submit

You definitely don't, because most of the time they'll be cut off or covered by the Observable UI. Sorry that I didn't state that more clearly. :)
