### ISSUE TITLE
View helper

### ISSUE THREAD

**Issue by j-f1** [observablehq/inputs#75]
I’m not sure how useful this would actually be but I thought it might be worth surfacing for potential addition to the library. I created a [View Helper](https://observablehq.com/@j-f1/view-helper?collection=@j-f1/observable) library a while ago, which allows you to turn arbitrary HTML into a view using one of two APIs:

```js
view`... html source ....`(initialValue, rootNode => {
  // set up event listeners etc
  // write to `rootNode.value` to dispatch an `input` event
})

// or

view(createDOMNodeSomehow(), initialValue, rootNode => { ... })
```

This is kind of similar to `Input()` (except that it lets you render an HTML node) and to `bind()` (except that it doesn’t synchronize to another input; you could totally pass this input to `bind` though).

**Comment by mbostock** [comment]
I don’t think it’s appropriate to dispatch an *input* event whenever the value is assigned — native inputs don’t behave that way, so neither do Observable Inputs. If that’s gone, then, not sure what’s left…

Here’s one take on your increment button:

```js
viewof f = Object.assign(html`<form>
  <button type=button onclick=${event => {
    const {form} = event.currentTarget;
    ++form.value;
    form.dispatchEvent(new Event("input"));
  }}>Increment</button>
</form>`, {value: 0})
```

The Object.assign is awkward; Hypertext Literal doesn’t provide a way to set the value property on the form element (it only sets attributes).

With the set helper #52, that could be written as:

```js
viewof f = Object.assign(html`<form>
  <button type=button onclick=${event => {
    const {form} = event.currentTarget;
    set(form, form.value + 1);
  }}>Increment</button>
</form>`, {value: 0})
```

If set returned the passed-in input, then you could do something like

```js
viewof f = set(html`<form>
  <button type=button onclick=${event => {
    const {form} = event.currentTarget;
    set(form, form.value + 1);
  }}>Increment</button>
</form>`, 0)
```

If set could take an optional reducer, then you could do something like:

```js
viewof f = set(html`<form>
  <button type=button onclick=${event => set(event.currentTarget.form, x => x + 1)}>Increment</button>
</form>`, 0)
```

Maybe that’s enough?

**Comment by j-f1** [comment]
Maybe! My rationale for dispatching an `input` event whenever you change the value is that for the narrow case of updating the value of a DOM element being used as a view, it never makes sense for `viewof foo.value` and `foo` to produce different results (assuming they both execute at the same time), and the `input` event is what’s needed to sync them up.

Perhaps something like this?

```js
viewof f = view`... html source ....`(initialValue, (rootNode, setValue) => {
  // set up event listeners etc
  // call `setValue(newValue)` to update `rootNode.value` and dispatch an `input` event
})
```

Or, as an additional overload to the `set` function:

```js
viewof f = set(setValue => html`<form>
  <button type=button onclick=${event => setValue(x => x + 1)}>Increment</button>
</form>`, 0)
```

Here, `setValue(foo)` would call `set(viewof f, foo)`.

**Comment by j-f1** [comment]
…but perhaps I’m optimizing too much for magical/compact code rather than clear and understandable code.

**Comment by severo** [comment]
> My rationale for dispatching an input event whenever you change the value is that for the narrow case of updating the value of a DOM element being used as a view, it never makes sense for viewof foo.value and foo to produce different results

I also have wondered for the same reason about the right default: dispatching an `input` event or not (in https://observablehq.com/@severo/inputs-setter I even dedicated a Boolean option `dispatch` to choose the behavior).

**Comment by mbostock** [comment]
Folding this issue in #52.
