### ISSUE TITLE
invalidation of source in bind

### ISSUE THREAD

**Issue by severo** [observablehq/inputs#82]
In [bind](https://github.com/observablehq/inputs#bind) ([source](https://github.com/observablehq/inputs/blob/main/src/bind.js)) the event listener registered on `source` is removed if `target` is invalidated. The reverse is not true: the event listener registered on `target` is not removed if `source` is invalidated.

I think I understand the logic is that `target` is bound to the source at the same moment it's created (as with `bind(Range([0, 100]), viewof i)` in [example](https://observablehq.com/@observablehq/synchronized-inputs)) so that if the source is invalidated, the target will also be invalidated because the cell where it is created depends on it.

But I imagine it's totally possible to create input A, input B, then bind them together afterward in a third cell. In that case, the event listener registered on `target` would not be removed on `source` invalidation.

Maybe it deserves to be explained (better than I do) in the doc.

**Comment by severo** [comment]
I didn't expect such detailed documentation, thanks a lot, it's excellent!

**Comment by severo** [comment]
Could we reopen that issue?

I think the event listener registered on *source* should also be removed when *invalidation* resolves.

In the case I mentioned [above](https://github.com/observablehq/inputs/issues/82#issue-804619584), "to create input A, input B, then bind them together afterward in a third cell", there is no reason to assume the *target* will disappear from the DOM and be garbage collected when we "unbind" when the promise resolves. The changes in *target* will then still modify *source*.

I show the behavior here: https://observablehq.com/@severo/unbind-two-synchronized-inputs

Would there be any drawback to replace

~~~js
invalidation.then(() => source.removeEventListener(sourceEvent, onsource));
~~~

with

~~~js
invalidation.then(() => {
  source.removeEventListener(sourceEvent, onsource);
  target.addEventListener(eventof(target), ontarget);
});
~~~

?

**Comment by mbostock** [comment]
@severo That breaks a use case such as this:

https://observablehq.com/@mbostock/tangle

With Tangle, the bound input is often immediately invalidated on interaction because it causes the cell to be regenerated. But it still works because Tangle is listening to events on the window.

**Comment by severo** [comment]
wow, it's tricky!

Do you think there could be a solution in my use case? Or should I better use my own bind function?

**Comment by mbostock** [comment]
The answer is probably two separate invalidation promises (targetInvalidation and sourceInvalidation), or maybe an alternative signature that returns a function that you can call to disconnect the two, e.g.

```js
const unbind = bind(target, source);
await something;
unbind();
```

🤷

**Comment by severo** [comment]
Sure, sorry for not being clear, I was not asking how to do it (btw your answer is better than what I had thought, thanks a lot!), but if it could be implemented in some way in the library.

If I understand correctly, the implementation will stay unchanged. Again sorry for not understanding quickly :)
