### ISSUE TITLE
Text wrap rows in Table?

### ISSUE THREAD

**Issue by melaniewalsh** [observablehq/inputs#88]
The new Table input is amazing! My only issue is that I have some text overflowing beyond my column widths. So I wanted to voice the possible need for a text-wrap rows option.

**Comment by mbostock** [comment]
The Table is designed to have fixed-height rows for lazy rendering, so unfortunately this isn’t possible. You can probably cheat around it by passing a *format* function that returns HTML, but I wouldn’t recommend it as other things will break. Sorry, but thank you for the feedback and suggestion!

**Comment by pretend-student** [comment]
That makes sense. Thanks, Mike!

Here's my Table that could use [some text wrapping](https://observablehq.com/@mellymeldubs/the-goodreads-classics-sortable-table/2), just in case it's helpful to see

**Comment by melaniewalsh** [comment]
That makes sense. Thanks, Mike!

Here's [my Table](https://observablehq.com/@mellymeldubs/the-goodreads-classics-sortable-table/2) that could use some text wrapping, just in case it's helpful to see

(Also sorry that I just posted the same comment from a different GitHub account. It's an account that I use to test things for a class I'm teaching, and I forgot that I was logged in)

**Comment by mbostock** [comment]
Cool example! Thanks for sharing. 👏
