### ISSUE TITLE
Table min-height

### ISSUE THREAD

**Issue by clhenrick** [observablehq/inputs#96]
Currently the way the Table Input renders may cause its height to change if its input data array length is less than the max number of table rows it is set to display. This causes DOM layout shifts which can be rather distracting. 

One way to prevent this could be for the Table Input to accept an option for a fixed height. A downside of this solution would be the table would continue to take up vertical space, even when displaying no results, but I believe the benefit of not causing DOM layout shifts would be worth it. I suppose an "empty state" of some kind (such as a placeholder UI) might be helpful for this case as well so that a user is not confused by a blank chunk of the DOM when the table has an empty input data array.

**Comment by mbostock** [comment]
Retitled as a request to add a minHeight property to Table.

**Comment by draben** [comment]
I assume this enhancement would allow a user to specify a minHeight values larger than the current default table height.  To be safe, I thought I would add that request here.  I would benefit from the ability to render taller tables.

(Thanks for the excellent work.  Happy corporate Team owner here!)
